"""empty message

Revision ID: d869d3048dcf
Revises: a7a5e6e0b4fe
Create Date: 2024-10-14 21:56:55.652924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd869d3048dcf'
down_revision = 'a7a5e6e0b4fe'
branch_labels = None
depends_on = None
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
   op.add_column('users', sa.Column('email', sa.String(), nullable=False, server_default='default@example.com'))



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint("email", 'users',type_='unique')
        batch_op.drop_column('users','email')

    # ### end Alembic commands ###
